### ISSUE TITLE
Steps for using the design pattern selection extension from within the SmartCLIDE Che Theia instance

### ISSUE THREAD

**Issue by deanone** [eclipse-opensmartclide/smartclide-design-pattern-selection-theia#53]
Dear @nikosnikolaidis ,

I have started checking/testing the extensions/plugins integrated into the SmartCLIDE Che Theia instance. According to the table [here](https://github.com/eclipse-opensmartclide/smartclide-devfiles), the latest version of the IDE contains the design pattern selection extension.

I have tried to test this extension. In particular, I loaded on my Che Theia instance a simple toy project, and opened the side pane that contains the design pattern selection options, as shown in the following figure:

![screenshot_opensmartclide_4](https://user-images.githubusercontent.com/5978626/211766959-79a2d2db-0de7-4cbb-8294-5d54feb3830f.png)

However, I cannot understand what I need to do and what input I need to provide in order to test the extension. I have selected several design patterns from the drop down list, but nothing actually happened. Can you please guide me on how to use/test the extension?

Thank you in advance.

**Comment by nikosnikolaidis** [comment]
Dear @deanone,

The final version of this extension is not deployed.
So it isn't able to get the files of the project.

In any case we are going to add better documentation from the aspect of the end user.

**Comment by deanone** [comment]
@nikosnikolaidis ok I understand. So, how am I supposed to use the extension?

**Comment by nikosnikolaidis** [comment]
@deanone I added the appropriate documentation in the repo.
Can check it out and inform me if its sufficient?

(The new version of the extension its not deployed yet, so you cant test it right now)

**Comment by deanone** [comment]
@nikosnikolaidis I have merged the PR #54 . Now, I'll check the new documentation and try again to use the extension. So, I close the ticket for now, and I may re-open it if needed.

**Comment by nikosnikolaidis** [comment]
@deanone Try it out when the new version of Theia is deployed, and if there is problem let me know!
